#+title: Gnulinux
#+author: Erfan Mirshams
#+language: persian

* مقدمه + تاریخچه ریز
آقای ریچارد استالمن که سیستم عامل GNU رو در سال ۱۹۸۵ منتشر کرد که هدف اصلی این پروژه گسترش سیستم عاملی در راستای ارزش های نرم افزار آزاد و احترام به حریم خصوصی و آزادی کاربر بود. ایشون بنیاد نرم افزار آزاد افتتاح کرده  و به علاوه پروژه هایی از قبیل GCC و Emacs هم انجام داده. سیستم عامل گنو همون طور که از اسم مخففش پیداست (Gnu's not unix) سیستم عاملی مشابه سیستم عامل unix هست و از فلسفه های مشابه اون در منطق اجرای برنامه ها پیروی میکنه. در سال ۱۹۹۱ هم یک دانشجوی فنلاندی در زمان آقای لینوس توروالدز که الان پشت پروژه هایی همچون گیت هم هست، از ابزار های توسعه نرم افزار گنو استفاده کرد و کرنل لینوکس رو توسعه داد و لایسنس آزاد هم براش قرار داد. بعد از این قضیه این کرنل در پروژه گنو به عنوان کرنل اصلی سیستم عامل استفاده شد و امروزه بخاطر راحتی و خوش اسم بودن به سیستم عامل گنو/لینوکس بیشتر با اسم لینوکس اشاره میشه.
* قدم اول
طبق طبیعتی که این پروژه داره و نرم افزار آزاد هست، یه دو راهی که چه عرض کنم، هزار راهی اول کار جلوی کاربر هست که کدوم توزیع رو نصب کنه. یه کلیتی از توزیع های لینوکس رو میشه توی [[https:distrowatch.com][سایت distrowatch]] ببینید. توصیه من اینه که توزیع ها مخصوصا توزیع های just works مثل اوبونتو و لینوکس مینت و پاپ او اس و ... همشون در باطن عین همن و فرقی نداره کدوم رو نصب کنید. مهم محیط میز کاره (Desktop Environment) که پروژه های متنوعی از جمله gnome، kde، xfce، cinnamon  و تعداد کثیر دیگه ای موجوده. این اسامی که گفتم رو جستجو کنید محیطش رو ببینید. ببینید با کدوم بیشتر حال می کنید و نسخه از توزیع های بالا که گفتم  رو با اون محیط نصب کنید. مثلا kubuntu اوبونتو همراه با kde هست. نصب هم ویدیو های زیادی روی اینترنت هست که نصبش رو آموزش میدن و به مراتب از نصب ویندوز ساده تره با یه جستجوی ساده مثل "install filan distro on virtualbox" میتونید یاد بگیرید و انجام بدید و برید سراغ مراحل بعد و آموزش استفاده. چون اوبونتو پر نصب ترین توزیعه در ادامه بیشتر توضیحاتی که میدم در محیط اوبونتو خواهد بود ولی با یه سری تغییرات یا حتی بدون تغییرات قابل تعمیم به سایر توزیع هاست.
* قدم صفرم
تو این هدینگ می خوام دلایلی رو بگم که یک نفر نباید لینوکس بریزه:
- خیلی به گیمینگ می پردازه. (البته آپشن ماشین مجازی رو داره یا می تونه رو یه لپتاپ دیگه ای بریزه)، شرکت valve خیلی داره رو گیمینگ رو لینوکس سرمایه گذاری و سرویس های مثل steam و lutris و تعداد کثیری بازی روش موجوده ولی بازم هنوز با ویندوز فاصله معنی داری داره.
- ارادت و نیاز مبرم به برنامه های خاص که فقط نسخه ویندوز یا مک دارن. البته این مساله هست که برنامه جایگزین روی لینوکس زیاده ولی برنامه هایی مثل Adobe Suite اگه خیلی بهشون عادت دارید و نمی تونید یه workflow جدید یاد بگیرید. یا مثلا 3D Max و Katia و اینجور چیزا. در حوزه نرم افزار تنها IDE معروفی که روی لینوکس موجود نیست Visual Studio عه (VSCode روی لینوکس هست).
- حوصله یاد گرفتن مهارت جدید و یا گذروندن یه learning curve یکی دو هفته ای رو نداشته باشه.
- کامپیوترتون برای خودتون نباشه و کس دیگه ای هم قراره ازش استفاده کنه. تو این حالت هم از ماشین مجازی استفاده کنید.
- لپتاپ های مک که SOC های جدید اپل (M1) رو دارن دارید. قراره پشتیبانی اینا به کرنل اضافه بشه فکر کنم ولی فعلا وجود نداره.

* نصب
توضیح مراحل نصب کار به نسبت باطلیه چون سخت افزار ها فرق میکنه. ولی اگر سخت افزارتون خیلی جدید نباشه نباید به مشکل خاصی بخورید. توصیه می‌شه قبل نصب live mode بالا میارید و تست کنید (گزینه try ubuntu). [[https://odysee.com/@DistroTube:2/is-ubuntu-22.04-the-best-ubuntu-in-years:f][فیلم آموزش نصب اوبونتو.]]
انواع نصب:
1. نصب به عنوان تنها سیستم عامل: برای این کار حتما اطلاعات روی کامپیوتر رو backup بگیرید. موقع نصب هم گزینه erase all disks رو بزنید.
2. دوال بوت: نصب لینوکس همراه ویندوز و انتخاب بین اینها موقع بوت. برای اینکار به دوستی که بلده مراجعه کنید و خودتون سراغش نرید.
3. ماشین مجازی: اجرای سیستم عاملی درون سیستم عامل میزبان. نرم افزار های استفاده شده Virtualbox، VMware و ...

* نرم افزار ها
نرم افزار هایی که برای کار های روزمره تون ممکنه نیاز بشه:
1. مرورگر: هر مرورگری روی ویندوز موجوده روی لینوکس هم موجوده. فقط نصب مرورگر هایی که انحصاری ان مثل Google Chrome و Edge سخت تره و کلا توصیه نمی شه. به حریم شخصی خودتون احترام بذارید و یا Firefox بریزید یا اگر مرورگر Chromium base می خواید Chromium و Brave موجودن.
2. پخش فیلم و موزیک: MPV، VLC، Rhythmbox و کلی برنامه دیگه برای این منظور موجوده.
3. برای کار های طراحی مثلا شبیه PhotoShop گزینه هایی مثل GIMP و  Krita هست
4. برای طراحی های سه بعدی یا حتی تدوین Blender هم موجوده که توی ویندوز و مک هم محبوبه. برای تدوین البته Kdenlive هم هست
5. به تعداد کثیری هم text editor موجوده از Vim و Emacs گرفته تا VSCode و Notepadqq که شبیه Notepad++ تو ویندوزه.
این هم  [[https://wiki.installgentoo.com/index.php/List_of_recommended_GNU/Linux_software][یه لیست خیلی خوب و جامع از نرم افزار های در دسترس بر روی لینوکس.]]

* نصب نرم افزار
به طور کلی روش نصب نرم افزار روی لینوکس با ویندوز متفاوته که البته این از نقاط قوت اصلی این سیستم عامل هست. روی اوبونتو یک Software Center گرافیکی هست که برای اول کار اگر هنوز دستتون توی ترمینال راه نیفتاده اکثر پکیج های موجود رو می تونید از روی اون به حالتی شبیه نصب برنامه از روی PlayStore روی موبایل نصب کنید. توزیع های لینوکس خودشون هم Package Manager مخصوص خودشون رو دارن که از مخازن نرم افزار های موجود اون توزیع که توسعه دهنده هاش آزمایش کردن و تایید کردن روی سیستم شما نرم افزار نصب می کنه. اتفاقی که پشت پرده می افته پیچیده تر از این حرفاست و توزیع های مختلف از Package Manager های مختلف و فلسفه های مختلفی به طور مختلف بعضا برای توزیع نرم افزار استفاده می کنن ولی خب همین توضیحات داده شده برای اینکه اولا کار آدم راه بیفته کفایت می کنه. Ubuntu چون Debian based هست (Debian هم یه توزیع لینوکسه که بعد ها احتمالا سراغش برید) از apt استفاده میکنه. توضیح کتابی دستور apt اولش ممکنه گیچ کننده باشه برای همین یه چند تا مثال ازش می زنیم خودتون وقتی باهاش دوست شدید بیشتر راجع بهش بخونید.
** یه چند تا مثال
ترمینال رو باز کنید. یا از طریق منوی برنامه ها یا توی اوبونتو با کلید های CTRL + ALT + T.
*** دستور بروزرسانی کامل سیستم
#+begin_src shell
sudo apt update && sudo apt upgrade
#+end_src
داخل گیومه این رو هم بگم که قبل دستوری sudo بزنید یه چیزی مشابه Run as Admin روی ویندوزه (اصلا شبیه نیست ولی فعلا توضیج بهتری ندارم) و ازتون پسورد خواهد خواست بعد زدن این دستور. اکثر اوقات هم داخل توزیع ها وقتی داخل ترمینال پسورد رو وارد میکنید تعداد کاراکتراشو برای مسائل امنیتی نشون نمیده (فکر نکنید کیبوردتون رو نمی خونه). و از جاهایی که sudo به کار میاد برای حذف و اضافه نرم افزار و بروزرسانی سیستم هست.
*** دستور نصب نرم افزار
#+begin_src shell
sudo apt install <package_name>
#+end_src
به جای package اسم پکیج درخواستی تون رو بزنید. مثلا برای نصب Htop از دستور زیر استفاده کنید. Htop یه سیستم مانیتوره توی ترمینال (مشابه Task Manager)
#+begin_src shell
sudo apt install htop
#+end_src
*** دستور حذف نرم افزار
#+begin_src shell
sudo apt remove <package_name>
#+end_src
*** دستور جستجوی نرم افزار
برای اینکه ببینید اسم دقیق پکیج یه نرم افزار چیه و آیا اصلا توی مخازن دیفالت apt موجوده یا که خیر
#+begin_src shell
apt search <package_name>
#+end_src
دقت کنید که اینجا نیازی به sudo نداریم.
*** مشاهده لیست پکیج های نصب شده
#+begin_src shell
apt list --installed
#+end_src
فعلا همین دستور ها برای شروع کار کافیه.
** اسفاده از Synaptic
روی سیستم هایی که از apt استفاده میکنن synaptic package manager هم موجوده که یه چیزی بین حالت گرافیکی و حالت CLI هست. از اون هم برای حذف و اضافه نرم افزار می تونید استفاده کنید. توی لیست نرم افزار هاتون Synaptic باید موجود باشه.

* نصب VSCode
به دلایلی که نمی دونم چرا VSCode توی مخازن اصلی اوبونتو و دبیان موجود نیست. برای همین برای نصبش یه راه روی اوبونتو پیشنهاد میدم. (تنها راه نیست)
ترمینال رو باز کنید و دستور زیر رو بزنید.
#+begin_src shell
sudo snap install --classic code
#+end_src
خودم خیلی با snap دوست نیستم ولی خب راه های دیگه که بود برای اول کار یخورده پیچیده بود و بچه ها اکثرا به VSCode برای کار هاشون نیاز دارن.
